# .github/workflows/docker-build.yml
name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Login sur Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et Push de l'image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            kyliangllt/mon-site:latest
            kyliangllt/mon-site:${{ github.sha }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Rolling update
        run: |
          kubectl rollout restart deployment mon-site-deployment -n kylian-exo-bonus1
          kubectl rollout status deployment mon-site-deployment -n kylian-exo-bonus1